/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package entryforms.filing;

import java.sql.Connection;
import java.sql.Statement;
import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import judgement.JudgementFormBean;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import common.plugin.DatabasePlugin;
/** 
 * MyEclipse Struts
 * Creation date: 07-28-2011
 * 
 * XDoclet definition:
 * @struts.action path="/ResetPassword" name="CASPFundsForm" scope="request" validate="true"
 */
public class ResetPasswordAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward unspecified(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response) throws Exception {
		Connection con=null;
		/*String[] user;*/
		try{
			con=DatabasePlugin.connect();
			JudgementFormBean jfbform = (JudgementFormBean) form;
			jfbform.reset(mapping, request);
			jfbform.setProperty("HODS",DatabasePlugin.getLabelValueBean(con, "select userid,(userid||'--'||username) from app_user_mst  order by userid", true));
			jfbform.setProperty("password","");
			jfbform.setProperty("confirmPassword","");
		}catch (Exception e) {
			e.printStackTrace();
		}
		finally{
			try{
				if(con!=null)
					con.close();
			}catch (Exception e2) {
				e2.printStackTrace();
			}
		}
		return mapping.findForward("resetPassword");
	}

	public ActionForward resetPassword(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {

		Connection con=null;
		Statement st=null;
		String sql=null;
		try{


			con=DatabasePlugin.connect();

			st=con.createStatement();
			JudgementFormBean CASPFundsForm = (JudgementFormBean) form;

			sql="update app_user_mst set passwd='"+CASPFundsForm.getProperty("password")+"' where userid='"+CASPFundsForm.getProperty("hodCode")+"'";
			System.out.println("sql="+sql);
			int i=st.executeUpdate(sql);
			if(i>0)
			{
				CASPFundsForm.setProperty("msg","The Password has been Reset successfully");
			}
			else
			{
				CASPFundsForm.setProperty("status","resetPassword");
				CASPFundsForm.setProperty("msg","Error occured while reset password, Try Again.");
			}				

		}
		catch(Exception e)
		{
			e.printStackTrace();
		}
		finally
		{
			try{
				if(con!=null)
					con.close();
			}catch (Exception e2) {
				e2.printStackTrace();
			}
		}
		return mapping.findForward("resetPassword");
	}
}