/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package in.apcfss.struts.Forms;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/**
 * MyEclipse Struts Creation date: 02-04-2020
 * 
 * XDoclet definition:
 * 
 * @struts.form name="manageUsersForm"
 */
public class ManageUsersForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** userRoleId property */
	private String userRoleId;

	/** userId property */
	private String userId;
	private String userSlNo;
	private String userPassword;

	/** userName property */
	private String userName;

	/** userDescription property */
	private String userDescription;

	private String userMobileNo, userEmail;

	/*
	 * Generated Methods
	 */

	/**
	 * Method validate
	 * 
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/**
	 * Method reset
	 * 
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/**
	 * Returns the userRoleId.
	 * 
	 * @return String
	 */
	public String getUserRoleId() {
		return userRoleId;
	}

	/**
	 * Set the userRoleId.
	 * 
	 * @param userRoleId
	 *            The userRoleId to set
	 */
	public void setUserRoleId(String userRoleId) {
		this.userRoleId = userRoleId;
	}

	/**
	 * Returns the userId.
	 * 
	 * @return String
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * Set the userId.
	 * 
	 * @param userId
	 *            The userId to set
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * Returns the userName.
	 * 
	 * @return String
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * Set the userName.
	 * 
	 * @param userName
	 *            The userName to set
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * Returns the userDescription.
	 * 
	 * @return String
	 */
	public String getUserDescription() {
		return userDescription;
	}

	/**
	 * Set the userDescription.
	 * 
	 * @param userDescription
	 *            The userDescription to set
	 */
	public void setUserDescription(String userDescription) {
		this.userDescription = userDescription;
	}

	public String getUserSlNo() {
		return userSlNo;
	}

	public void setUserSlNo(String userSlNo) {
		this.userSlNo = userSlNo;
	}

	public String getUserPassword() {
		return userPassword;
	}

	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	public String getUserMobileNo() {
		return userMobileNo;
	}

	public void setUserMobileNo(String userMobileNo) {
		this.userMobileNo = userMobileNo;
	}

	public String getUserEmail() {
		return userEmail;
	}

	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}
}