/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package in.apcfss.struts.Forms;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 02-04-2020
 * 
 * XDoclet definition:
 * @struts.form name="rolesManagementForm"
 */
public class RoleManagementForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** roleDescription property */
	private String roleDescription;

	/** roleName property */
	private String roleName;

	/** roleId property */
	private String roleId;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the roleDescription.
	 * @return String
	 */
	public String getRoleDescription() {
		return roleDescription;
	}

	/** 
	 * Set the roleDescription.
	 * @param roleDescription The roleDescription to set
	 */
	public void setRoleDescription(String roleDescription) {
		this.roleDescription = roleDescription;
	}

	/** 
	 * Returns the roleName.
	 * @return String
	 */
	public String getRoleName() {
		return roleName;
	}

	/** 
	 * Set the roleName.
	 * @param roleName The roleName to set
	 */
	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	/** 
	 * Returns the roleId.
	 * @return String
	 */
	public String getRoleId() {
		return roleId;
	}

	/** 
	 * Set the roleId.
	 * @param roleId The roleId to set
	 */
	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}
}